# Generated by Django 5.0.3 on 2024-03-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="complete",
            field=models.BooleanField(default=False),
        ),
    ]
